#flags
MAINFLAGS = -Wall -w -ansi -pedantic
CLASSFLAGS = -Wall -w -ansi -pedantic -c

#paths
OUTPATH = ./bin/
OBJPATH = ./obj/
SRCPATH = ./src/

#Filepaths for cpp
MAINCPP = $(SRCPATH)main.cpp
GLOBALSCPP = $(SRCPATH)Globals.cpp
ENTITYCPP = $(SRCPATH)Entity.cpp
CHARACTERCPP =$(SRCPATH)Character.cpp
PLAYERCPP = $(SRCPATH)Player.cpp
FIGMENTCPP = $(SRCPATH)Figment.cpp
BATTLECPP = $(SRCPATH)Battle.cpp
ABILITYCPP = $(SRCPATH)Ability.cpp
INFOCPP = $(SRCPATH)Info.cpp
ITEMCPP = $(SRCPATH)Item.cpp
FOODCPP = $(SRCPATH)Food.cpp
HEALTHPERCENTAGECPP = $(SRCPATH)HealthPercentage.cpp

#Filepaths for h
GLOBALSH = $(SRCPATH)Globals.h
ENTITYH = $(SRCPATH)Entity.h
CHARACTERH =$(SRCPATH)Character.h
PLAYERH = $(SRCPATH)Player.h
FIGMENTH = $(SRCPATH)Figment.h
BATTLEH = $(SRCPATH)Battle.h
ABILITYH = $(SRCPATH)Ability.h
INFOH = $(SRCPATH)Info.h
ITEMH = $(SRCPATH)Item.h
FOODH = $(SRCPATH)Food.h
HEALTHPERCENTAGEH = $(SRCPATH)HealthPercentage.h

#Filepaths for o
MAINO = $(OBJPATH)Main.o
GLOBALSO = $(OBJPATH)Globals.o
ENTITYO = $(OBJPATH)Entity.o
CHARACTERO =$(OBJPATH)Character.o
PLAYERO = $(OBJPATH)Player.o
FIGMENTO = $(OBJPATH)Figment.o
BATTLEO = $(OBJPATH)Battle.o
ABILITYO = $(OBJPATH)Ability.o
INFOO = $(OBJPATH)Info.o
ITEMO = $(OBJPATH)Item.o
FOODO = $(OBJPATH)Food.o
HEALTHPERCENTAGEO = $(OBJPATH)HealthPercentage.o

#final executable
EXE = $(OUTPATH)debug

game: create $(OUTPATH)debug run

create:
	mkdir -p ./bin/
	mkdir -p ./obj/
clean:
	rm -rf ./bin/
	rm -rf ./obj/
run:
	bin/debug

$(EXE): $(MAINO) 
	g++ $(MAINFLAGS) $(MAINO) $(GLOBALSO) $(ENTITYO) $(CHARACTERO) $(PLAYERO) $(FIGMENTO) $(BATTLEO) $(ABILITYO) $(INFOO) $(ILLUMINITEO) -o $(EXE)
	
$(MAINO): $(INFOO) $(ABILITYO) $(PLAYERO) $(FIGMENTO) $(BATTLEO) $(MAINCPP) 
	g++ $(CLASSFLAGS) $(MAINCPP) -o $(MAINO)
	
$(GLOBALSO): $(GLOBALSCPP) $(GLOBALSH)
	g++ $(CLASSFLAGS) $(GLOBALSCPP) -o $(GLOBALSO)
	
$(ENTITYO): $(ENTITYCPP) $(ENTITYH)
	g++ $(CLASSFLAGS) $(ENTITYCPP) -o $(ENTITYO)
	
$(CHARACTERO): $(ENTITYO) $(GLOBALSO) $(CHARACTERCPP) $(CHARACTERH)
	g++ $(CLASSFLAGS) $(CHARACTERCPP) -o $(CHARACTERO)
	
$(PLAYERO): $(CHARACTERO) $(ABILITYO) $(PLAYERCPP) $(PLAYERH)
	g++ $(CLASSFLAGS) $(PLAYERCPP) -o $(PLAYERO)
	
$(FIGMENTO): $(GLOBALSO) $(CHARACTERO) $(ABILITYO) $(FIGMENTCPP) $(FIGMENTH)
	g++ $(CLASSFLAGS) $(FIGMENTCPP) -o $(FIGMENTO)
	
$(BATTLEO): $(GLOBALSO) $(PLAYERO) $(FIGMENTO) $(INFOO) $(BATTLECPP) $(BATTLEH)
	g++ $(CLASSFLAGS) $(BATTLECPP) -o $(BATTLEO)
	
$(ABILITYO): $(ENTITYO) $(GLOBALSO) $(CHARACTERO) $(ABILITYCPP) $(ABILITYH)
	g++ $(CLASSFLAGS) $(ABILITYCPP) -o $(ABILITYO)
	
$(ITEMO): $(GLOBALSO) $(ENTITYO) $(CHARACTERO) $(ITEMCPP) $(ITEMH)
	g++ $(CLASSFLAGS) $(ITEMCPP) -o $(ITEMO)

$(FOODO): $(ITEMO) $(CHARACTERO) $(FOODCPP) $(FOODH)
	g++ $(CLASSFLAGS) $(FOODCPP) -o $(FOODO)

$(INFOO): $(ABILITYO) $(ITEMO) $(HEALTHPERCENTAGEO) $(GLOBALSO) $(INFOCPP) $(INFOH)
	g++ $(CLASSFLAGS) $(INFOCPP) -o $(INFOO)
	
$(HEALTHPERCENTAGEO): $(FOODO) $(CHARACTERO) $(HEALTHPERCENTAGECPP) $(HEALTHPERCENTAGEH)
	g++ $(CLASSFLAGS) $(HEALTHPERCENTAGECPP) -o $(HEALTHPERCENTAGEO)
